import React, { useState } from 'react';
import { ArrowRight, Beaker, BookOpen, Brain, CheckCircle2, FlaskConical, Sparkles, Target } from 'lucide-react';
import { CONCEPT_NODES, GOAL_LABELS, LearnerProfile } from '../../data/adaptiveLearning';
import { AdaptiveState, getNextConcept, getMasteryAverage, recordPrediction as recordPredictionEvent, recordResourceCheck } from '../../utils/adaptive';
import { OnboardingFlow } from './OnboardingFlow';
import { AdaptiveExperiment } from './AdaptiveExperiment';

type AppTab = 'dashboard' | 'curriculum' | 'composer' | 'bloch' | 'sandbox' | 'quiz';
interface Props { state: AdaptiveState; onProfile: (profile: LearnerProfile) => void; onState: (state: AdaptiveState) => void; onNavigate: (tab: AppTab) => void; onOpenAI: () => void; }

export const AdaptiveHome: React.FC<Props> = ({ state, onProfile, onState, onNavigate, onOpenAI }) => {
  const [resourceVerification, setResourceVerification] = useState<{ conceptId: string; understood: boolean } | null>(null);
  if (!state.profile) return <OnboardingFlow onComplete={onProfile} />;
  const next = getNextConcept(state);
  const average = getMasteryAverage(state);
  const goal = GOAL_LABELS[state.profile.goal];
  const verified = resourceVerification?.conceptId === next.id ? resourceVerification.understood : null;
  const verifyResource = (understood: boolean) => { setResourceVerification({ conceptId: next.id, understood }); onState(recordResourceCheck(state, next.id, understood)); };
  const recordPrediction = (correct: boolean) => onState(recordPredictionEvent(state, next.id, correct));
  return <div className="space-y-8 py-5">
    <section className="relative overflow-hidden rounded-[2rem] glass-panel p-7 sm:p-10"><div className="orb orb-blue w-72 h-72 -top-32 right-[8%] opacity-50" /><div className="relative z-10 grid lg:grid-cols-[1.15fr_.85fr] gap-8 items-center"><div>
      <div className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[.2em] text-zinc-500"><Sparkles className="w-3.5 h-3.5 text-[#dfff3f]" /> Adaptive learning workspace</div>
      <h1 className="text-4xl sm:text-6xl font-semibold tracking-tight mt-5 text-zinc-100">Your quantum path,<br /><span className="template-accent">not a fixed course.</span></h1>
      <p className="max-w-2xl text-sm sm:text-base leading-7 text-zinc-400 mt-5">You are learning to <span className="text-zinc-200">{goal.toLowerCase()}</span>. QubitLab uses your answers and experiments to choose what you should do next.</p>
      <div className="flex flex-wrap gap-3 mt-7"><button onClick={() => onNavigate('dashboard')} className="template-button px-5 py-3 rounded-xl text-sm font-semibold flex items-center gap-2">View my path <ArrowRight className="w-4 h-4" /></button><button onClick={onOpenAI} className="px-5 py-3 rounded-xl bg-white/5 border border-white/10 text-sm text-zinc-300 flex items-center gap-2"><Brain className="w-4 h-4" /> Ask the guide</button></div>
    </div><div className="glass-card rounded-2xl p-5"><div className="flex justify-between items-start"><div><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Current mastery</div><div className="text-4xl font-semibold text-zinc-100 mt-2">{average}%</div></div><Target className="w-6 h-6 text-[#dfff3f]" /></div><div className="h-2 rounded-full bg-white/5 mt-5 overflow-hidden"><div className="h-full bg-[#dfff3f]" style={{ width: `${average}%` }} /></div><div className="grid grid-cols-2 gap-3 mt-5 text-xs"><Metric label="Prediction accuracy" value={`${state.predictionAccuracy}%`} /><Metric label="Learning signals" value={`${state.journalCount} runs`} /></div></div></div></section>
    <section className="grid lg:grid-cols-[1.2fr_.8fr] gap-6"><div className="glass-section rounded-2xl p-6"><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Next best action</div><h2 className="text-2xl font-semibold text-zinc-100 mt-2">{next.title}</h2></div><span className="text-[10px] font-mono text-[#dfff3f]">{next.duration} MIN</span></div><p className="text-sm text-zinc-400 leading-6 mt-3">{next.objective}</p><div className="grid md:grid-cols-2 gap-3 mt-5"><button onClick={() => onNavigate('composer')} className="rounded-xl border border-[#dfff3f]/25 bg-[#dfff3f]/5 p-4 text-left hover:border-[#dfff3f]/50 transition-all"><Beaker className="w-5 h-5 text-[#dfff3f]" /><div className="text-sm font-semibold text-zinc-100 mt-3">Open full Quantum Lab</div><div className="text-xs text-zinc-500 mt-1">Build the circuit yourself after the guided mission.</div></button><button onClick={() => onNavigate('curriculum')} className="rounded-xl border border-white/10 bg-black/25 p-4 text-left hover:border-white/25 transition-all"><BookOpen className="w-5 h-5 text-indigo-300" /><div className="text-sm font-semibold text-zinc-100 mt-3">Learn the concept</div><div className="text-xs text-zinc-500 mt-1">Read, visualize, then test yourself.</div></button></div>
    {next.resource && <div className="mt-4 rounded-xl border border-white/10 bg-black/25 p-4 space-y-4"><div className="flex items-center justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.18em] text-zinc-600">Recommended resource · {next.resource.type}</div><div className="text-sm text-zinc-200 mt-1">{next.resource.title}</div></div><span className="text-[10px] font-mono text-zinc-500">{next.resource.duration}</span></div>{next.resource.url && <a href={next.resource.url} target="_blank" rel="noreferrer" className="inline-flex px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-[11px] text-zinc-300 hover:border-[#dfff3f]/40">Open resource ↗</a>}{verified === null ? <div className="rounded-lg border border-white/5 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[.16em] text-zinc-600">After learning</div><div className="text-xs text-zinc-300 mt-1">Could you now explain this concept without looking at the resource?</div><div className="flex gap-2 mt-3"><button onClick={() => verifyResource(true)} className="px-3 py-1.5 rounded-md bg-emerald-500/10 border border-emerald-500/20 text-[10px] text-emerald-300">Yes, I can</button><button onClick={() => verifyResource(false)} className="px-3 py-1.5 rounded-md bg-white/5 border border-white/10 text-[10px] text-zinc-400">Not yet</button></div></div> : <div className={`text-xs ${verified ? 'text-emerald-300' : 'text-amber-300'}`}>{verified ? 'Verified. Your mastery was updated.' : 'No problem. QubitLab will keep this concept in your learning loop.'}</div>}</div>}
    </div><div className="glass-section rounded-2xl p-6"><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Learning loop</div><div className="space-y-4 mt-5">{['Diagnose', 'Predict', 'Experiment', 'Explain', 'Verify', 'Adapt'].map((item, index) => <div key={item} className="flex items-center gap-3"><div className={`w-7 h-7 rounded-lg flex items-center justify-center text-[10px] font-mono ${index < 2 ? 'bg-[#dfff3f]/15 text-[#dfff3f]' : 'bg-white/5 text-zinc-500'}`}>{index + 1}</div><span className="text-sm text-zinc-300">{item}</span>{index < 5 && <div className="h-px flex-1 bg-white/5" />}</div>)}</div></div></section>
    <AdaptiveExperiment key={next.id} concept={next} onComplete={recordPrediction} onAskAI={onOpenAI} />
    <section className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{CONCEPT_NODES.slice(0, 6).map((node) => { const mastery = state.mastery[node.id] ?? 0; return <div key={node.id} className="glass-card rounded-2xl p-5"><div className="flex justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.16em] text-zinc-600">{node.category}</div><h3 className="text-sm font-semibold text-zinc-100 mt-1">{node.title}</h3></div>{mastery >= 80 ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <FlaskConical className="w-4 h-4 text-zinc-600" />}</div><div className="mt-4 h-1.5 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-[#dfff3f]" style={{ width: `${mastery}%` }} /></div><div className="text-[10px] font-mono text-zinc-500 mt-2">{mastery}% mastery</div></div>; })}</section>
  </div>;
};
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-black/30 border border-white/5 p-3"><div className="text-[10px] text-zinc-600">{label}</div><div className="text-sm font-mono text-zinc-200 mt-1">{value}</div></div>; }
