import { GoogleGenAI } from '@google/genai';

function getGeminiApiKey(): string | undefined {
  const rawKey = process.env.GEMINI_API_KEY || process.env.API_KEY;
  if (!rawKey) return undefined;
  const cleanKey = rawKey.trim().replace(/^["']|["']$/g, '');
  if (!cleanKey || cleanKey === 'MY_GEMINI_API_KEY' || cleanKey === 'placeholder') return undefined;
  return cleanKey;
}

function getAIClient(): GoogleGenAI | null {
  const apiKey = getGeminiApiKey();
  if (!apiKey) return null;
  return new GoogleGenAI({
    apiKey,
    httpOptions: { headers: { 'User-Agent': 'QubitLab-Vercel' } },
  });
}

function formatMessagesForGemini(rawMessages: Array<{ role: string; content: string }>) {
  const contents: Array<{ role: 'user' | 'model'; parts: Array<{ text: string }> }> = [];

  for (const m of rawMessages) {
    if (!m || typeof m.content !== 'string' || !m.content.trim()) continue;
    const role: 'user' | 'model' = m.role === 'assistant' || m.role === 'model' ? 'model' : 'user';
    if (contents.length === 0 && role !== 'user') continue;

    if (contents.length > 0 && contents[contents.length - 1].role === role) {
      contents[contents.length - 1].parts[0].text += `\n\n${m.content.trim()}`;
    } else {
      contents.push({ role, parts: [{ text: m.content.trim() }] });
    }
  }

  if (contents.length === 0) {
    contents.push({
      role: 'user',
      parts: [{ text: 'Explain the quantum state and operations currently being explored.' }],
    });
  }

  return contents;
}

function fallbackReply(messages: Array<{ role: string; content: string }>) {
  const lastUserMsg = [...messages].reverse().find(m => m.role === 'user')?.content?.toLowerCase() || '';

  if (lastUserMsg.includes('hadamard') || lastUserMsg.includes('h gate')) {
    return `### The Hadamard Gate (H)\nThe Hadamard gate maps computational basis states into balanced superpositions:\n- $H|0\\rangle = |+\\rangle = \\frac{1}{\\sqrt{2}}(|0\\rangle + |1\\rangle)$\n- $H|1\\rangle = |-\\rangle = \\frac{1}{\\sqrt{2}}(|0\\rangle - |1\\rangle)$\n\nApplying H twice returns the state back: $H^2 = I$.`;
  }

  if (lastUserMsg.includes('entangle') || lastUserMsg.includes('bell')) {
    return `### Quantum Entanglement & Bell States\nEntanglement occurs when a multi-qubit state cannot be written as a product of individual qubit states.\n\nThe Bell state $|\\Phi^+\\rangle = \\frac{|00\\rangle + |11\\rangle}{\\sqrt{2}}$ is generated by applying H to the first qubit and then CNOT with that qubit as control.`;
  }

  if (lastUserMsg.includes('grover')) {
    return `### Grover's Search Algorithm\nGrover's algorithm provides a quadratic speedup for unstructured search over $N=2^n$ items, using $O(\\sqrt{N})$ oracle queries. The main stages are equal superposition, oracle phase inversion, and amplitude amplification.`;
  }

  if (lastUserMsg.includes('bloch') || lastUserMsg.includes('sphere')) {
    return `### The Bloch Sphere\nA pure single-qubit state can be represented as $|\\psi\\rangle = \\cos(\\theta/2)|0\\rangle + e^{i\\phi}\\sin(\\theta/2)|1\\rangle$. The north pole is $|0\\rangle$, the south pole is $|1\\rangle$, and the equator contains balanced superpositions.`;
  }

  return `Quantum computing uses linear algebra in Hilbert space:\n- **Superposition:** $|\\psi\\rangle = \\alpha|0\\rangle + \\beta|1\\rangle$ where $|\\alpha|^2+|\\beta|^2=1$.\n- **Unitary evolution:** quantum gates satisfy $U^\\dagger U=I$.\n- **Born rule:** $P(x)=|\\langle x|\\psi\\rangle|^2$.`;
}

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { context, messages } = req.body || {};
    if (!Array.isArray(messages)) {
      return res.status(400).json({ error: 'Messages array is required' });
    }

    const ai = getAIClient();
    if (!ai) return res.status(200).json({ reply: fallbackReply(messages) });

    const systemPrompt = `You are QubitLab's Quantum Computing Tutor, an expert physicist and quantum computing professor.\nYou explain quantum mechanics, quantum circuits, quantum algorithms (Grover, Deutsch-Jozsa, Shor, VQE), Dirac bra-ket notation, Qiskit/Cirq code, and hardware concepts clearly, intuitively, and mathematically accurately.\nWhen explaining circuits, reference the user's current circuit state if provided in context.\nUse standard mathematical notation and concise, educational language.\nContext provided:\n${context || 'No specific circuit context provided.'}`;

    const formattedContents = formatMessagesForGemini(messages);
    let replyText = '';
    const modelsToTry = ['gemini-3.1-flash-lite', 'gemini-3.8-flash'];

    for (const model of modelsToTry) {
      try {
        const response = await ai.models.generateContent({
          model,
          contents: formattedContents,
          config: { systemInstruction: systemPrompt, temperature: 0.6, maxOutputTokens: 1200 },
        });
        if (response.text?.trim()) {
          replyText = response.text.trim();
          break;
        }
      } catch (modelErr) {
        console.warn(`Gemini model ${model} failed`, modelErr);
      }
    }

    if (!replyText) return res.status(200).json({ reply: fallbackReply(messages) });
    return res.status(200).json({ reply: replyText });
  } catch (error: any) {
    console.error('Gemini API Error:', error);
    return res.status(500).json({ error: error?.message || 'Failed to generate tutor response' });
  }
}
